#!/usr/bin/env bash
# Script to install and configure Nginx web server

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Ensure Nginx is listening on port 80
sudo sed -i 's/listen\s*80;/listen 80;/g' /etc/nginx/sites-available/default
# Reload Nginx configuration
service nginx reload

# Create index.html with "Hello World!" content
echo "Hello World!" > /usr/share/nginx/html/index.html

# Check if Nginx is running
if pgrep -x "nginx" >/dev/null
then
    echo "Nginx installed and configured successfully!"
else
    echo "Failed to install or configure Nginx!"
fi
