#!/usr/bin/env bash
# Configures a new Ubuntu machine to install and set up Nginx

# Update package list and install nginx
apt-get update -y
apt-get install nginx -y

# Ensure Nginx is listening on port 80
sed -i 's/^\(listen\s*80\)/# \1/' /etc/nginx/sites-available/default
echo "listen 80;" >> /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

# Create a simple index.html with "Hello World!"
echo "Hello World!" > /var/www/html/index.html
