#!/usr/bin/env bash
# Installs, configures, and starts the server with redirection

# Update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Start nginx (it may start automatically, but this ensures it's running)
sudo service nginx start

# Create a default Nginx configuration file
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/redirected_page;
    }
}
EOF'
# create an index.html file with the string Hello, World!
echo "Hello, World" | sudo tee /var/www/html/index.html > /dev/null
# Reload Nginx to apply the new configuration
sudo service nginx reload

# Output a message indicating successful configuration
echo "Nginx installed and configured. Server is now listening on port 80 with redirection."
