#!/usr/bin/env bash

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Set the hostnames for the servers
sudo hostnamectl set-hostname "333119-web-01"
sudo echo "333119-web-01" > /etc/hostname
sudo sed -i "s/^127.0.1.1.*/127.0.1.1\t333119-web-01/g" /etc/hosts

sudo hostnamectl set-hostname "333119-web-02"
sudo echo "333119-web-02" > /etc/hostname
sudo sed -i "s/^127.0.1.1.*/127.0.1.1\t333119-web-02/g" /etc/hosts

# Install HAProxy on the server
apt-get -y update
apt-get -y install haproxy

# Define HAProxy configuration
haproxy_config="/etc/haproxy/haproxy.cfg"
cat <<EOF | sudo tee "$haproxy_config" > /dev/null
frontend evahaudi_frontend
    bind *:80
    mode http
    default_backend evahaudi_backend
    timeout client 30s

backend evahaudi_backend
    balance roundrobin
    mode http
    option http-server-close
    option forwardfor
    server 333119-web-01 127.0.0.1:80 check
    server 333119-web-02 127.0.0.1:80 check
    timeout server 30s
    timeout connect 5s
    timeout client 30s
EOF

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# Test the HAProxy configuration file
sudo haproxy -c -f "$haproxy_config"

# Restart the HAProxy service
sudo service haproxy restart
