#!/bin/bash

# Update repositories and install necessary packages
apt-get update
apt-get install -y nginx

# Modify Nginx configuration to listen on port 80
sed -i 's/^\(\s*listen\s*80;\)/# \1\nlisten 80;/' /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
service nginx restart
