#!/usr/bin/env bash
# A script that Configures nginx to run and listen to port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
#sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
