#!/usr/bin/env bash
# Description: Gracefully restart Gunicorn
# Check if Gunicorn process is running
if pgrep gunicorn > /dev/null; then
    # Gracefully restart Gunicorn
    pgrep gunicorn | xargs kill -HUP
    
    # Print "OK" after successfully restarting Gunicorn
    echo "OK"
else
    # Print an error message if Gunicorn is not running
    echo "Gunicorn is not running"
fi
